services:
  - type: web
    name: thai-road-accident-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DSP:server
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.10.12